export interface VulnerablePackage {
  name: string;
  versions: string; // Simplified for client-side matching
  description: string;
}

export const VULNERABLE_PACKAGES: VulnerablePackage[] = [
  { name: 'backslash', versions: '0.2.1', description: 'A utility for working with backslashes.' },
  { name: 'chalk-template', versions: '1.1.1', description: 'A template literal tag for chalk.' },
  { name: 'supports-hyperlinks', versions: '4.1.1', description: 'Detect whether a terminal supports hyperlinks.' },
  { name: 'has-ansi', versions: '6.0.1', description: 'Check if a string has ANSI escape codes.' },
  { name: 'simple-swizzle', versions: '0.2.3', description: 'A simple swizzle utility.' },
  { name: 'color-string', versions: '2.1.1', description: 'Parser and generator for color strings.' },
  { name: 'error-ex', versions: '1.3.3', description: 'Extend native Error object.' },
  { name: 'color-name', versions: '2.0.1', description: 'A list of color names and their values.' },
  { name: 'is-arrayish', versions: '0.3.3', description: 'Check if a value is array-like.' },
  { name: 'slice-ansi', versions: '7.1.1', description: 'Slice a string with ANSI escape codes.' },
  { name: 'color-convert', versions: '3.1.1', description: 'A color conversion utility.' },
  { name: 'wrap-ansi', versions: '9.0.1', description: 'Word-wrap a string with ANSI escape codes.' },
  { name: 'ansi-regex', versions: '6.2.1', description: 'Regular expression for matching ANSI escape codes.' },
  { name: 'supports-color', versions: '10.2.1', description: 'Detect whether a terminal supports color.' },
  { name: 'strip-ansi', versions: '7.1.1', description: 'Strip ANSI escape codes from a string.' },
  { name: 'chalk', versions: '5.6.1', description: 'Terminal string styling done right.' },
  { name: 'debug', versions: '4.4.2', description: 'A tiny JavaScript debugging utility.' },
  { name: 'ansi-styles', versions: '6.2.2', description: 'ANSI escape codes for styling strings in the terminal.' },
  { name: '@ahmedhfarag/ngx-perfect-scrollbar', versions: '20.0.20', description: 'Angular wrapper for the perfect-scrollbar library.' },
  { name: '@ahmedhfarag/ngx-virtual-scroller', versions: '4.0.4', description: 'Virtual scroller for Angular applications.' },
  { name: '@art-ws/common', versions: '2.0.28', description: 'Common utilities for Art-WS projects.' },
  { name: '@art-ws/config-eslint', versions: '2.0.4, 2.0.5', description: 'ESLint configuration for Art-WS projects.' },
  { name: '@art-ws/config-ts', versions: '2.0.7, 2.0.8', description: 'TypeScript configuration for Art-WS projects.' },
  { name: '@art-ws/db-context', versions: '2.0.24', description: 'Database context for Art-WS projects.' },
  { name: '@art-ws/di', versions: '2.0.28, 2.0.32', description: 'Dependency injection for Art-WS projects.' },
  { name: '@art-ws/di-node', versions: '2.0.13', description: 'Node.js dependency injection for Art-WS projects.' },
  { name: '@art-ws/eslint', versions: '1.0.5, 1.0.6', description: 'ESLint related utilities for Art-WS.' },
  { name: '@art-ws/fastify-http-server', versions: '2.0.24, 2.0.27', description: 'Fastify HTTP server for Art-WS projects.' },
  { name: '@art-ws/http-server', versions: '2.0.21, 2.0.25', description: 'HTTP server utilities for Art-WS projects.' },
  { name: '@art-ws/openapi', versions: '0.1.9, 0.1.12', description: 'OpenAPI utilities for Art-WS projects.' },
  { name: '@art-ws/package-base', versions: '1.0.5, 1.0.6', description: 'Base package for Art-WS projects.' },
  { name: '@art-ws/prettier', versions: '1.0.5, 1.0.6', description: 'Prettier configuration for Art-WS projects.' },
  { name: '@art-ws/slf', versions: '2.0.15, 2.0.22', description: 'Logging framework for Art-WS projects.' },
  { name: '@art-ws/ssl-info', versions: '1.0.9, 1.0.10', description: 'SSL information utility for Art-WS projects.' },
  { name: '@art-ws/web-app', versions: '1.0.3, 1.0.4', description: 'Web application utilities for Art-WS projects.' },
  { name: '@crowdstrike/commitlint', versions: '8.1.1, 8.1.2', description: 'Commitlint configuration for CrowdStrike projects.' },
  { name: '@crowdstrike/falcon-shoelace', versions: '0.4.1, 0.4.2', description: 'Falcon design system components based on Shoelace.' },
  { name: '@crowdstrike/foundry-js', versions: '0.19.1, 0.19.2', description: 'JavaScript library for CrowdStrike Foundry.' },
  { name: '@crowdstrike/glide-core', versions: '0.34.2, 0.34.3', description: 'Core components for Glide, a data grid library.' },
  { name: '@crowdstrike/logscale-dashboard', versions: '1.205.1, 1.205.2', description: 'Dashboard components for CrowdStrike LogScale.' },
  { name: '@crowdstrike/logscale-file-editor', versions: '1.205.1, 1.205.2', description: 'File editor for CrowdStrike LogScale.' },
  { name: '@crowdstrike/logscale-parser-edit', versions: '1.205.1, 1.205.2', description: 'Parser editor for CrowdStrike LogScale.' },
  { name: '@crowdstrike/logscale-search', versions: '1.205.1, 1.205.2', description: 'Search components for CrowdStrike LogScale.' },
  { name: '@crowdstrike/tailwind-toucan-base', versions: '5.0.1, 5.0.2', description: 'Base Tailwind CSS configuration for CrowdStrike Toucan.' },
  { name: '@ctrl/deluge', versions: '7.2.1, 7.2.2', description: 'A Deluge client for Node.js.' },
  { name: '@ctrl/golang-template', versions: '1.4.2, 1.4.3', description: 'Go-style template parsing and execution in JavaScript.' },
  { name: '@ctrl/magnet-link', versions: '4.0.3, 4.0.4', description: 'A magnet link parser.' },
  { name: '@ctrl/ngx-codemirror', versions: '7.0.1, 7.0.2', description: 'CodeMirror component for Angular.' },
  { name: '@ctrl/ngx-csv', versions: '6.0.1, 6.0.2', description: 'A CSV export utility for Angular.' },
  { name: '@ctrl/ngx-emoji-mart', versions: '9.2.1, 9.2.2', description: 'Emoji Mart component for Angular.' },
  { name: '@ctrl/ngx-rightclick', versions: '4.0.1, 4.0.2', description: 'Right-click context menu for Angular.' },
  { name: '@ctrl/qbittorrent', versions: '9.7.1, 9.7.2', description: 'A qBittorrent client for Node.js.' },
  { name: '@ctrl/react-adsense', versions: '2.0.1, 2.0.2', description: 'React component for Google AdSense.' },
  { name: '@ctrl/shared-torrent', versions: '6.3.1, 6.3.2', description: 'Shared torrent utilities.' },
  { name: '@ctrl/tinycolor', versions: '4.1.1, 4.1.2', description: 'A small, fast color manipulation and conversion library.' },
  { name: '@ctrl/torrent-file', versions: '4.1.1, 4.1.2', description: 'A torrent file parser and creator.' },
  { name: '@ctrl/transmission', versions: '7.3.1', description: 'A Transmission client for Node.js.' },
  { name: '@ctrl/ts-base32', versions: '4.0.1, 4.0.2', description: 'Base32 encoding and decoding in TypeScript.' },
  { name: '@hestjs/core', versions: '0.2.1', description: 'Core framework for Hestjs applications.' },
  { name: '@hestjs/cqrs', versions: '0.1.6', description: 'CQRS module for Hestjs.' },
  { name: '@hestjs/demo', versions: '0.1.2', description: 'Demo application for Hestjs.' },
  { name: '@hestjs/eslint-config', versions: '0.1.2', description: 'ESLint configuration for Hestjs projects.' },
  { name: '@hestjs/logger', versions: '0.1.6', description: 'Logger module for Hestjs.' },
  { name: '@hestjs/scalar', versions: '0.1.7', description: 'Scalar types for Hestjs.' },
  { name: '@hestjs/validation', versions: '0.1.6', description: 'Validation module for Hestjs.' },
  { name: '@nativescript-community/arraybuffers', versions: '1.1.6, 1.1.7, 1.1.8', description: 'Array buffer utilities for NativeScript.' },
  { name: '@nativescript-community/gesturehandler', versions: '2.0.35', description: 'Gesture handler for NativeScript.' },
  { name: '@nativescript-community/perms', versions: '3.0.5, 3.0.6, 3.0.7, 3.0.8', description: 'Permissions handler for NativeScript.' },
  { name: '@nativescript-community/sqlite', versions: '3.5.2, 3.5.3, 3.5.4, 3.5.5', description: 'SQLite plugin for NativeScript.' },
  { name: '@nativescript-community/text', versions: '1.6.9, 1.6.10, 1.6.11, 1.6.12', description: 'Advanced text components for NativeScript.' },
  { name: '@nativescript-community/typeorm', versions: '0.2.30, 0.2.31, 0.2.32, 0.2.33', description: 'TypeORM integration for NativeScript.' },
  { name: '@nativescript-community/ui-collectionview', versions: '6.0.6', description: 'CollectionView UI component for NativeScript.' },
  { name: '@nativescript-community/ui-document-picker', versions: '1.1.27, 1.1.28', description: 'Document picker for NativeScript.' },
  { name: '@nativescript-community/ui-drawer', versions: '0.1.30', description: 'Drawer (side navigation) UI component for NativeScript.' },
  { name: '@nativescript-community/ui-image', versions: '4.5.6', description: 'Advanced image components for NativeScript.' },
  { name: '@nativescript-community/ui-label', versions: '1.3.35, 1.3.36, 1.3.37', description: 'Advanced label components for NativeScript.' },
  { name: '@nativescript-community/ui-material-bottom-navigation', versions: '7.2.72, 7.2.73, 7.2.74, 7.2.75', description: 'Material Design bottom navigation for NativeScript.' },
  { name: '@nativescript-community/ui-material-bottomsheet', versions: '7.2.72', description: 'Material Design bottom sheet for NativeScript.' },
  { name: '@nativescript-community/ui-material-core', versions: '7.2.72, 7.2.73, 7.2.74, 7.2.75', description: 'Core components for Material Design in NativeScript.' },
  { name: '@nativescript-community/ui-material-core-tabs', versions: '7.2.72, 7.2.73, 7.2.74, 7.2.75', description: 'Material Design tabs core for NativeScript.' },
  { name: '@nativescript-community/ui-material-ripple', versions: '7.2.72, 7.2.73, 7.2.74, 7.2.75', description: 'Material Design ripple effect for NativeScript.' },
  { name: '@nativescript-community/ui-material-tabs', versions: '7.2.72, 7.2.73, 7.2.74, 7.2.75', description: 'Material Design tabs for NativeScript.' },
  { name: '@nativescript-community/ui-pager', versions: '14.1.36, 14.1.37, 14.1.38', description: 'Pager UI component for NativeScript.' },
  { name: '@nativescript-community/ui-pulltorefresh', versions: '2.5.4, 2.5.5, 2.5.6, 2.5.7', description: 'Pull-to-refresh component for NativeScript.' },
  { name: '@nexe/config-manager', versions: '0.1.1', description: 'Configuration manager for Nexe.' },
  { name: '@nexe/eslint-config', versions: '0.1.1', description: 'ESLint configuration for Nexe.' },
  { name: '@nexe/logger', versions: '0.1.3', description: 'Logger for Nexe.' },
  { name: '@nstudio/angular', versions: '20.0.4, 20.0.5, 20.0.6', description: 'Angular utilities for NStudio projects.' },
  { name: '@nstudio/focus', versions: '20.0.4, 20.0.5, 20.0.6', description: 'Focus management for NStudio projects.' },
  { name: '@nstudio/nativescript-checkbox', versions: '2.0.6, 2.0.7, 2.0.8, 2.0.9', description: 'Checkbox component for NativeScript.' },
  { name: '@nstudio/nativescript-loading-indicator', versions: '5.0.1, 5.0.2, 5.0.3, 5.0.4', description: 'Loading indicator for NativeScript.' },
  { name: '@nstudio/ui-collectionview', versions: '5.1.11, 5.1.12, 5.1.13, 5.1.14', description: 'CollectionView UI component for NStudio.' },
  { name: '@nstudio/web', versions: '20.0.4', description: 'Web utilities for NStudio projects.' },
  { name: '@nstudio/web-angular', versions: '20.0.4', description: 'Angular web utilities for NStudio projects.' },
  { name: '@nstudio/xplat', versions: '20.0.5, 20.0.6, 20.0.7', description: 'Cross-platform tools for NStudio.' },
  { name: '@nstudio/xplat-utils', versions: '20.0.5, 20.0.6, 20.0.7', description: 'Utilities for NStudio xplat.' },
  { name: '@operato/board', versions: '9.0.36, 9.0.37, 9.0.38, 9.0.39, 9.0.40, 9.0.41, 9.0.42, 9.0.43, 9.0.44, 9.0.45, 9.0.46', description: 'Board component for Operato.' },
  { name: '@operato/data-grist', versions: '9.0.29, 9.0.35, 9.0.36, 9.0.37', description: 'Data grist component for Operato.' },
  { name: '@operato/graphql', versions: '9.0.22, 9.0.35, 9.0.36, 9.0.37, 9.0.38, 9.0.39, 9.0.40, 9.0.41, 9.0.42, 9.0.43, 9.0.44, 9.0.45, 9.0.46', description: 'GraphQL client for Operato.' },
  { name: '@operato/headroom', versions: '9.0.2, 9.0.35, 9.0.36, 9.0.37', description: 'Headroom component for Operato.' },
  { name: '@operato/help', versions: '9.0.35, 9.0.36, 9.0.37, 9.0.38, 9.0.39, 9.0.40, 9.0.41, 9.0.42, 9.0.43, 9.0.44, 9.0.45, 9.0.46', description: 'Help components for Operato.' },
  { name: '@operato/i18n', versions: '9.0.35, 9.0.36, 9.0.37', description: 'Internationalization utilities for Operato.' },
  { name: '@operato/input', versions: '9.0.27, 9.0.35, 9.0.36, 9.0.37, 9.0.38, 9.0.39, 9.0.40, 9.0.41, 9.0.42, 9.0.43, 9.0.44, 9.0.45, 9.0.46', description: 'Input components for Operato.' },
  { name: '@operato/layout', versions: '9.0.35, 9.0.36, 9.0.37', description: 'Layout components for Operato.' },
  { name: '@operato/popup', versions: '9.0.22, 9.0.35, 9.0.36, 9.0.37, 9.0.38, 9.0.39, 9.0.40, 9.0.41, 9.0.42, 9.0.43, 9.0.44, 9.0.45, 9.0.46', description: 'Popup component for Operato.' },
  { name: '@operato/pull-to-refresh', versions: '9.0.36, 9.0.37, 9.0.38, 9.0.39, 9.0.40, 9.0.41, 9.0.42', description: 'Pull-to-refresh component for Operato.' },
  { name: '@operato/shell', versions: '9.0.22, 9.0.35, 9.0.36, 9.0.37, 9.0.38, 9.0.39', description: 'Shell component for Operato.' },
  { name: '@operato/styles', versions: '9.0.2, 9.0.35, 9.0.36, 9.0.37', description: 'Styles for Operato components.' },
  { name: '@operato/utils', versions: '9.0.22, 9.0.35, 9.0.36, 9.0.37, 9.0.38, 9.0.39, 9.0.40, 9.0.41, 9.0.42, 9.0.43, 9.0.44, 9.0.45, 9.0.46', description: 'Utilities for Operato.' },
  { name: '@teselagen/bounce-loader', versions: '0.3.16, 0.3.17', description: 'A bounce loader component.' },
  { name: '@teselagen/liquibase-tools', versions: '0.4.1', description: 'Liquibase tools for TeselaGen.' },
  { name: '@teselagen/range-utils', versions: '0.3.14, 0.3.15', description: 'Range utilities for TeselaGen.' },
  { name: '@teselagen/react-list', versions: '0.8.19, 0.8.20', description: 'A virtualized list component for React.' },
  { name: '@teselagen/react-table', versions: '6.10.19', description: 'A table component for React.' },
  { name: '@thangved/callback-window', versions: '1.1.4', description: 'A callback window utility.' },
  { name: '@things-factory/attachment-base', versions: '9.0.43, 9.0.44, 9.0.45, 9.0.46, 9.0.47, 9.0.48, 9.0.49, 9.0.50', description: 'Attachment base for Things Factory.' },
  { name: '@things-factory/auth-base', versions: '9.0.43, 9.0.44, 9.0.45', description: 'Authentication base for Things Factory.' },
  { name: '@things-factory/email-base', versions: '9.0.42, 9.0.43, 9.0.44, 9.0.45, 9.0.46, 9.0.47, 9.0.48, 9.0.49, 9.0.50, 9.0.51, 9.0.52, 9.0.53, 9.0.54', description: 'Email base for Things Factory.' },
  { name: '@things-factory/env', versions: '9.0.42, 9.0.43, 9.0.44, 9.0.45', description: 'Environment utilities for Things Factory.' },
  { name: '@things-factory/integration-base', versions: '9.0.43, 9.0.44, 9.0.45', description: 'Integration base for Things Factory.' },
  { name: '@things-factory/integration-marketplace', versions: '9.0.43, 9.0.44, 9.0.45', description: 'Integration marketplace for Things Factory.' },
  { name: '@things-factory/shell', versions: '9.0.43, 9.0.44, 9.0.45', description: 'Shell for Things Factory applications.' },
  { name: '@tnf-dev/api', versions: '1.0.8', description: 'API utilities for TNF-Dev.' },
  { name: '@tnf-dev/core', versions: '1.0.8', description: 'Core utilities for TNF-Dev.' },
  { name: '@tnf-dev/js', versions: '1.0.8', description: 'JavaScript utilities for TNF-Dev.' },
  { name: '@tnf-dev/mui', versions: '1.0.8', description: 'Material-UI components for TNF-Dev.' },
  { name: '@tnf-dev/react', versions: '1.0.8', description: 'React utilities for TNF-Dev.' },
  { name: '@ui-ux-gang/devextreme-angular-rpk', versions: '24.1.7', description: 'DevExtreme Angular components repackaged.' },
  { name: '@yoobic/design-system', versions: '6.5.17', description: 'Yoobic design system components.' },
  { name: '@yoobic/jpeg-camera-es6', versions: '1.0.13', description: 'ES6 JPEG camera utility.' },
  { name: '@yoobic/yobi', versions: '8.7.53', description: 'Yoobic main application package.' },
  { name: 'airchief', versions: '0.3.1', description: 'A utility for managing air-gapped environments.' },
  { name: 'airpilot', versions: '0.8.8', description: 'A tool for piloting applications.' },
  { name: 'angulartics2', versions: '14.1.1, 14.1.2', description: 'Vendor-agnostic analytics for Angular applications.' },
  { name: 'browser-webdriver-downloader', versions: '3.0.8', description: 'A tool to download browser WebDrivers.' },
  { name: 'capacitor-notificationhandler', versions: '0.0.2, 0.0.3', description: 'Notification handler plugin for Capacitor.' },
  { name: 'capacitor-plugin-healthapp', versions: '0.0.2, 0.0.3', description: 'Health app plugin for Capacitor.' },
  { name: 'capacitor-plugin-ihealth', versions: '1.1.8, 1.1.9', description: 'iHealth plugin for Capacitor.' },
  { name: 'capacitor-plugin-vonage', versions: '1.0.2, 1.0.3', description: 'Vonage plugin for Capacitor.' },
  { name: 'capacitorandroidpermissions', versions: '0.0.4, 0.0.5', description: 'Android permissions plugin for Capacitor.' },
  { name: 'config-cordova', versions: '0.8.5', description: 'Configuration tool for Cordova.' },
  { name: 'cordova-plugin-voxeet2', versions: '1.0.24', description: 'Voxeet plugin for Cordova.' },
  { name: 'cordova-voxeet', versions: '1.0.32', description: 'Legacy Voxeet plugin for Cordova.' },
  { name: 'create-hest-app', versions: '0.1.9', description: 'CLI to create a new Hestjs application.' },
  { name: 'db-evo', versions: '1.1.4, 1.1.5', description: 'Database evolution tool.' },
  { name: 'devextreme-angular-rpk', versions: '21.2.8', description: 'Repackaged DevExtreme components for Angular.' },
  { name: 'ember-browser-services', versions: '5.0.2, 5.0.3', description: 'Browser services for Ember applications.' },
  { name: 'ember-headless-form', versions: '1.1.2, 1.1.3', description: 'Headless form components for Ember.' },
  { name: 'ember-headless-form-yup', versions: '1.0.1', description: 'Yup validation for ember-headless-form.' },
  { name: 'ember-headless-table', versions: '2.1.5, 2.1.6', description: 'Headless table components for Ember.' },
  { name: 'ember-url-hash-polyfill', versions: '1.0.12, 1.0.13', description: 'URL hash polyfill for Ember.' },
  { name: 'ember-velcro', versions: '2.2.1, 2.2.2', description: 'A component for anchoring elements in Ember.' },
  { name: 'encounter-playground', versions: '0.0.2, 0.0.3, 0.0.4, 0.0.5', description: 'A playground for FHIR encounters.' },
  { name: 'eslint-config-crowdstrike', versions: '11.0.2, 11.0.3', description: 'ESLint configuration for CrowdStrike.' },
  { name: 'eslint-config-crowdstrike-node', versions: '4.0.3, 4.0.4', description: 'Node.js ESLint configuration for CrowdStrike.' },
  { name: 'eslint-config-teselagen', versions: '6.1.7', description: 'ESLint configuration for TeselaGen.' },
  { name: 'globalize-rpk', versions: '1.7.4', description: 'Repackaged Globalize library.' },
  { name: 'graphql-sequelize-teselagen', versions: '5.3.8', description: 'GraphQL and Sequelize integration for TeselaGen.' },
  { name: 'html-to-base64-image', versions: '1.0.2', description: 'Convert HTML to a base64 image.' },
  { name: 'json-rules-engine-simplified', versions: '0.2.1', description: 'A simplified rules engine using JSON.' },
  { name: 'jumpgate', versions: '0.0.2', description: 'A component library.' },
  { name: 'koa2-swagger-ui', versions: '5.11.1, 5.11.2', description: 'Swagger UI for Koa2.' },
  { name: 'mcfly-semantic-release', versions: '1.3.1', description: 'Semantic release configuration for McFly.' },
  { name: 'mcp-knowledge-base', versions: '0.0.2', description: 'Knowledge base for MCP.' },
  { name: 'mcp-knowledge-graph', versions: '1.2.1', description: 'Knowledge graph for MCP.' },
  { name: 'mobioffice-cli', versions: '1.0.3', description: 'CLI for MobiOffice.' },
  { name: 'monorepo-next', versions: '13.0.1, 13.0.2', description: 'Next.js utilities for monorepos.' },
  { name: 'mstate-angular', versions: '0.4.4', description: 'State management for Angular.' },
  { name: 'mstate-cli', versions: '0.4.7', description: 'CLI for mstate.' },
  { name: 'mstate-dev-react', versions: '1.1.1', description: 'Dev tools for mstate in React.' },
  { name: 'mstate-react', versions: '1.6.5', description: 'State management for React.' },
  { name: 'ng2-file-upload', versions: '7.0.2, 7.0.3, 8.0.1, 8.0.2, 8.0.3, 9.0.1', description: 'File upload component for Angular 2.' },
  { name: 'ngx-bootstrap', versions: '18.1.4, 19.0.3, 19.0.4, 20.0.3, 20.0.4, 20.0.5', description: 'Bootstrap components for Angular.' },
  { name: 'ngx-color', versions: '10.0.1, 10.0.2', description: 'Color picker for Angular.' },
  { name: 'ngx-toastr', versions: '19.0.1, 19.0.2', description: 'Toast notifications for Angular.' },
  { name: 'ngx-trend', versions: '8.0.1', description: 'Trend component for Angular.' },
  { name: 'ngx-ws', versions: '1.1.5, 1.1.6', description: 'WebSocket module for Angular.' },
  { name: 'oradm-to-gql', versions: '35.0.14, 35.0.15', description: 'A tool to convert Orad-M to GraphQL.' },
  { name: 'oradm-to-sqlz', versions: '1.1.2', description: 'A tool to convert Orad-M to Sequelize.' },
  { name: 'ove-auto-annotate', versions: '0.0.9', description: 'Auto-annotation tool for OVE.' },
  { name: 'pm2-gelf-json', versions: '1.0.4, 1.0.5', description: 'PM2 GELF JSON logging module.' },
  { name: 'printjs-rpk', versions: '1.6.1', description: 'Repackaged Print.js library.' },
  { name: 'react-complaint-image', versions: '0.0.32', description: 'Image complaint component for React.' },
  { name: 'react-jsonschema-form-conditionals', versions: '0.3.18', description: 'Conditional logic for react-jsonschema-form.' },
  { name: 'remark-preset-lint-crowdstrike', versions: '4.0.1, 4.0.2', description: 'Remark lint preset for CrowdStrike.' },
  { name: 'rxnt-authentication', versions: '0.0.3, 0.0.4, 0.0.5, 0.0.6', description: 'Authentication library for RxNT.' },
  { name: 'rxnt-healthchecks-nestjs', versions: '1.0.2, 1.0.3, 1.0.4, 1.0.5', description: 'Health checks for NestJS in RxNT.' },
  { name: 'rxnt-kue', versions: '1.0.4, 1.0.5, 1.0.6, 1.0.7', description: 'Kue job queue for RxNT.' },
  { name: 'swc-plugin-component-annotate', versions: '1.9.1, 1.9.2', description: 'SWC plugin for component annotation.' },
  { name: 'tbssnch', versions: '1.0.2', description: 'A utility package.' },
  { name: 'teselagen-interval-tree', versions: '1.1.2', description: 'Interval tree implementation for TeselaGen.' },
  { name: 'tg-client-query-builder', versions: '2.14.4, 2.14.5', description: 'Client query builder for TeselaGen.' },
  { name: 'tg-redbird', versions: '1.3.1', description: 'Redbird reverse proxy for TeselaGen.' },
  { name: 'tg-seq-gen', versions: '1.0.9, 1.0.10', description: 'Sequence generation for TeselaGen.' },
  { name: 'thangved-react-grid', versions: '1.0.3', description: 'React grid component.' },
  { name: 'ts-gaussian', versions: '3.0.5, 3.0.6', description: 'Gaussian distribution library for TypeScript.' },
  { name: 'ts-imports', versions: '1.0.1, 1.0.2', description: 'TypeScript import management tool.' },
  { name: 'tvi-cli', versions: '0.1.5', description: 'CLI for TVI.' },
  { name: 've-bamreader', versions: '0.2.6', description: 'BAM file reader for VectorEditor.' },
  { name: 've-editor', versions: '1.0.1', description: 'Vector Editor component.' },
  { name: 'verror-extra', versions: '6.0.1', description: 'Extra utilities for VError.' },
  { name: 'voip-callkit', versions: '1.0.2, 1.0.3', description: 'CallKit plugin for VoIP applications.' },
  { name: 'wdio-web-reporter', versions: '0.1.3', description: 'Web reporter for WebdriverIO.' },
  { name: 'yargs-help-output', versions: '5.0.3', description: 'Generate help output for yargs.' },
  { name: 'yoo-styles', versions: '6.0.326', description: 'Styles for Yoo applications.' }
];
