export interface VulnerablePackage {
  name: string;
  versions: string; // Simplified for client-side matching
  description: string;
}

export const VULNERABLE_PACKAGES: VulnerablePackage[] = [
  { name: 'backslash', versions: '0.2.1', description: 'Una utilidad para trabajar con barras invertidas.' },
  { name: 'chalk-template', versions: '1.1.1', description: 'Una etiqueta de plantilla literal para chalk.' },
  { name: 'supports-hyperlinks', versions: '4.1.1', description: 'Detecta si un terminal admite hipervínculos.' },
  { name: 'has-ansi', versions: '6.0.1', description: 'Comprueba si una cadena tiene códigos de escape ANSI.' },
  { name: 'simple-swizzle', versions: '0.2.3', description: 'Una utilidad simple de swizzle.' },
  { name: 'color-string', versions: '2.1.1', description: 'Analizador y generador de cadenas de color.' },
  { name: 'error-ex', versions: '1.3.3', description: 'Extiende el objeto Error nativo.' },
  { name: 'color-name', versions: '2.0.1', description: 'Una lista de nombres de colores y sus valores.' },
  { name: 'is-arrayish', versions: '0.3.3', description: 'Comprueba si un valor es similar a un array.' },
  { name: 'slice-ansi', versions: '7.1.1', description: 'Corta una cadena con códigos de escape ANSI.' },
  { name: 'color-convert', versions: '3.1.1', description: 'Una utilidad de conversión de color.' },
  { name: 'wrap-ansi', versions: '9.0.1', description: 'Envuelve una cadena con códigos de escape ANSI.' },
  { name: 'ansi-regex', versions: '6.2.1', description: 'Expresión regular para buscar códigos de escape ANSI.' },
  { name: 'supports-color', versions: '10.2.1', description: 'Detecta si un terminal admite color.' },
  { name: 'strip-ansi', versions: '7.1.1', description: 'Elimina los códigos de escape ANSI de una cadena.' },
  { name: 'chalk', versions: '5.6.1', description: 'Estiliza cadenas en el terminal.' },
  { name: 'debug', versions: '4.4.2', description: 'Una pequeña utilidad de depuración de JavaScript.' },
  { name: 'ansi-styles', versions: '6.2.2', description: 'Códigos de escape ANSI para estilizar cadenas en el terminal.' },
  { name: '@ahmedhfarag/ngx-perfect-scrollbar', versions: '20.0.20', description: 'Wrapper de Angular para la librería perfect-scrollbar.' },
  { name: '@ahmedhfarag/ngx-virtual-scroller', versions: '4.0.4', description: 'Scroller virtual para aplicaciones Angular.' },
  { name: '@art-ws/common', versions: '2.0.28', description: 'Utilidades comunes para proyectos de Art-WS.' },
  { name: '@art-ws/config-eslint', versions: '2.0.4, 2.0.5', description: 'Configuración de ESLint para proyectos de Art-WS.' },
  { name: '@art-ws/config-ts', versions: '2.0.7, 2.0.8', description: 'Configuración de TypeScript para proyectos de Art-WS.' },
  { name: '@art-ws/db-context', versions: '2.0.24', description: 'Contexto de base de datos para proyectos de Art-WS.' },
  { name: '@art-ws/di', versions: '2.0.28, 2.0.32', description: 'Inyección de dependencias para proyectos de Art-WS.' },
  { name: '@art-ws/di-node', versions: '2.0.13', description: 'Inyección de dependencias de Node.js para proyectos de Art-WS.' },
  { name: '@art-ws/eslint', versions: '1.0.5, 1.0.6', description: 'Utilidades relacionadas con ESLint para Art-WS.' },
  { name: '@art-ws/fastify-http-server', versions: '2.0.24, 2.0.27', description: 'Servidor HTTP Fastify para proyectos de Art-WS.' },
  { name: '@art-ws/http-server', versions: '2.0.21, 2.0.25', description: 'Utilidades de servidor HTTP para proyectos de Art-WS.' },
  { name: '@art-ws/openapi', versions: '0.1.9, 0.1.12', description: 'Utilidades OpenAPI para proyectos de Art-WS.' },
  { name: '@art-ws/package-base', versions: '1.0.5, 1.0.6', description: 'Paquete base para proyectos de Art-WS.' },
  { name: '@art-ws/prettier', versions: '1.0.5, 1.0.6', description: 'Configuración de Prettier para proyectos de Art-WS.' },
  { name: '@art-ws/slf', versions: '2.0.15, 2.0.22', description: 'Framework de logging para proyectos de Art-WS.' },
  { name: '@art-ws/ssl-info', versions: '1.0.9, 1.0.10', description: 'Utilidad de información SSL para proyectos de Art-WS.' },
  { name: '@art-ws/web-app', versions: '1.0.3, 1.0.4', description: 'Utilidades de aplicación web para proyectos de Art-WS.' },
  { name: '@crowdstrike/commitlint', versions: '8.1.1, 8.1.2', description: 'Configuración de Commitlint para proyectos de CrowdStrike.' },
  { name: '@crowdstrike/falcon-shoelace', versions: '0.4.1, 0.4.2', description: 'Componentes del sistema de diseño Falcon basados en Shoelace.' },
  { name: '@crowdstrike/foundry-js', versions: '0.19.1, 0.19.2', description: 'Librería de JavaScript para CrowdStrike Foundry.' },
  { name: '@crowdstrike/glide-core', versions: '0.34.2, 0.34.3', description: 'Componentes principales para Glide, una librería de cuadrícula de datos.' },
  { name: '@crowdstrike/logscale-dashboard', versions: '1.205.1, 1.205.2', description: 'Componentes de dashboard para CrowdStrike LogScale.' },
  { name: '@crowdstrike/logscale-file-editor', versions: '1.205.1, 1.205.2', description: 'Editor de archivos para CrowdStrike LogScale.' },
  { name: '@crowdstrike/logscale-parser-edit', versions: '1.205.1, 1.205.2', description: 'Editor de analizadores para CrowdStrike LogScale.' },
  { name: '@crowdstrike/logscale-search', versions: '1.205.1, 1.205.2', description: 'Componentes de búsqueda para CrowdStrike LogScale.' },
  { name: '@crowdstrike/tailwind-toucan-base', versions: '5.0.1, 5.0.2', description: 'Configuración base de Tailwind CSS para CrowdStrike Toucan.' },
  { name: '@ctrl/deluge', versions: '7.2.1, 7.2.2', description: 'Un cliente de Deluge para Node.js.' },
  { name: '@ctrl/golang-template', versions: '1.4.2, 1.4.3', description: 'Análisis y ejecución de plantillas al estilo Go en JavaScript.' },
  { name: '@ctrl/magnet-link', versions: '4.0.3, 4.0.4', description: 'Un analizador de enlaces magnet.' },
  { name: '@ctrl/ngx-codemirror', versions: '7.0.1, 7.0.2', description: 'Componente CodeMirror para Angular.' },
  { name: '@ctrl/ngx-csv', versions: '6.0.1, 6.0.2', description: 'Una utilidad de exportación de CSV para Angular.' },
  { name: '@ctrl/ngx-emoji-mart', versions: '9.2.1, 9.2.2', description: 'Componente Emoji Mart para Angular.' },
  { name: '@ctrl/ngx-rightclick', versions: '4.0.1, 4.0.2', description: 'Menú contextual de clic derecho para Angular.' },
  { name: '@ctrl/qbittorrent', versions: '9.7.1, 9.7.2', description: 'Un cliente de qBittorrent para Node.js.' },
  { name: '@ctrl/react-adsense', versions: '2.0.1, 2.0.2', description: 'Componente de React para Google AdSense.' },
  { name: '@ctrl/shared-torrent', versions: '6.3.1, 6.3.2', description: 'Utilidades compartidas de torrent.' },
  { name: '@ctrl/tinycolor', versions: '4.1.1, 4.1.2', description: 'Una pequeña y rápida librería de manipulación y conversión de colores.' },
  { name: '@ctrl/torrent-file', versions: '4.1.1, 4.1.2', description: 'Un analizador y creador de archivos torrent.' },
  { name: '@ctrl/transmission', versions: '7.3.1', description: 'Un cliente de Transmission para Node.js.' },
  { name: '@ctrl/ts-base32', versions: '4.0.1, 4.0.2', description: 'Codificación y decodificación Base32 en TypeScript.' },
  { name: '@hestjs/core', versions: '0.2.1', description: 'Framework principal para aplicaciones Hestjs.' },
  { name: '@hestjs/cqrs', versions: '0.1.6', description: 'Módulo CQRS para Hestjs.' },
  { name: '@hestjs/demo', versions: '0.1.2', description: 'Aplicación de demostración para Hestjs.' },
  { name: '@hestjs/eslint-config', versions: '0.1.2', description: 'Configuración de ESLint para proyectos Hestjs.' },
  { name: '@hestjs/logger', versions: '0.1.6', description: 'Módulo de logger para Hestjs.' },
  { name: '@hestjs/scalar', versions: '0.1.7', description: 'Tipos escalares para Hestjs.' },
  { name: '@hestjs/validation', versions: '0.1.6', description: 'Módulo de validación para Hestjs.' },
  { name: '@nativescript-community/arraybuffers', versions: '1.1.6, 1.1.7, 1.1.8', description: 'Utilidades de buffer de array para NativeScript.' },
  { name: '@nativescript-community/gesturehandler', versions: '2.0.35', description: 'Manejador de gestos para NativeScript.' },
  { name: '@nativescript-community/perms', versions: '3.0.5, 3.0.6, 3.0.7, 3.0.8', description: 'Manejador de permisos para NativeScript.' },
  { name: '@nativescript-community/sqlite', versions: '3.5.2, 3.5.3, 3.5.4, 3.5.5', description: 'Plugin de SQLite para NativeScript.' },
  { name: '@nativescript-community/text', versions: '1.6.9, 1.6.10, 1.6.11, 1.6.12', description: 'Componentes de texto avanzados para NativeScript.' },
  { name: '@nativescript-community/typeorm', versions: '0.2.30, 0.2.31, 0.2.32, 0.2.33', description: 'Integración de TypeORM para NativeScript.' },
  { name: '@nativescript-community/ui-collectionview', versions: '6.0.6', description: 'Componente de UI CollectionView para NativeScript.' },
  { name: '@nativescript-community/ui-document-picker', versions: '1.1.27, 1.1.28', description: 'Selector de documentos para NativeScript.' },
  { name: '@nativescript-community/ui-drawer', versions: '0.1.30', description: 'Componente de UI de cajón (navegación lateral) para NativeScript.' },
  { name: '@nativescript-community/ui-image', versions: '4.5.6', description: 'Componentes de imagen avanzados para NativeScript.' },
  { name: '@nativescript-community/ui-label', versions: '1.3.35, 1.3.36, 1.3.37', description: 'Componentes de etiqueta avanzados para NativeScript.' },
  { name: '@nativescript-community/ui-material-bottom-navigation', versions: '7.2.72, 7.2.73, 7.2.74, 7.2.75', description: 'Navegación inferior de Material Design para NativeScript.' },
  { name: '@nativescript-community/ui-material-bottomsheet', versions: '7.2.72', description: 'Hoja inferior de Material Design para NativeScript.' },
  { name: '@nativescript-community/ui-material-core', versions: '7.2.72, 7.2.73, 7.2.74, 7.2.75', description: 'Componentes principales para Material Design en NativeScript.' },
  { name: '@nativescript-community/ui-material-core-tabs', versions: '7.2.72, 7.2.73, 7.2.74, 7.2.75', description: 'Núcleo de pestañas de Material Design para NativeScript.' },
  { name: '@nativescript-community/ui-material-ripple', versions: '7.2.72, 7.2.73, 7.2.74, 7.2.75', description: 'Efecto de onda de Material Design para NativeScript.' },
  { name: '@nativescript-community/ui-material-tabs', versions: '7.2.72, 7.2.73, 7.2.74, 7.2.75', description: 'Pestañas de Material Design para NativeScript.' },
  { name: '@nativescript-community/ui-pager', versions: '14.1.36, 14.1.37, 14.1.38', description: 'Componente de UI de paginador para NativeScript.' },
  { name: '@nativescript-community/ui-pulltorefresh', versions: '2.5.4, 2.5.5, 2.5.6, 2.5.7', description: 'Componente de pull-to-refresh para NativeScript.' },
  { name: '@nexe/config-manager', versions: '0.1.1', description: 'Gestor de configuración para Nexe.' },
  { name: '@nexe/eslint-config', versions: '0.1.1', description: 'Configuración de ESLint para Nexe.' },
  { name: '@nexe/logger', versions: '0.1.3', description: 'Logger para Nexe.' },
  { name: '@nstudio/angular', versions: '20.0.4, 20.0.5, 20.0.6', description: 'Utilidades de Angular para proyectos de NStudio.' },
  { name: '@nstudio/focus', versions: '20.0.4, 20.0.5, 20.0.6', description: 'Gestión de foco para proyectos de NStudio.' },
  { name: '@nstudio/nativescript-checkbox', versions: '2.0.6, 2.0.7, 2.0.8, 2.0.9', description: 'Componente de checkbox para NativeScript.' },
  { name: '@nstudio/nativescript-loading-indicator', versions: '5.0.1, 5.0.2, 5.0.3, 5.0.4', description: 'Indicador de carga para NativeScript.' },
  { name: '@nstudio/ui-collectionview', versions: '5.1.11, 5.1.12, 5.1.13, 5.1.14', description: 'Componente de UI CollectionView para NStudio.' },
  { name: '@nstudio/web', versions: '20.0.4', description: 'Utilidades web para proyectos de NStudio.' },
  { name: '@nstudio/web-angular', versions: '20.0.4', description: 'Utilidades web de Angular para proyectos de NStudio.' },
  { name: '@nstudio/xplat', versions: '20.0.5, 20.0.6, 20.0.7', description: 'Herramientas multiplataforma para NStudio.' },
  { name: '@nstudio/xplat-utils', versions: '20.0.5, 20.0.6, 20.0.7', description: 'Utilidades para NStudio xplat.' },
  { name: '@operato/board', versions: '9.0.36, 9.0.37, 9.0.38, 9.0.39, 9.0.40, 9.0.41, 9.0.42, 9.0.43, 9.0.44, 9.0.45, 9.0.46', description: 'Componente de tablero para Operato.' },
  { name: '@operato/data-grist', versions: '9.0.29, 9.0.35, 9.0.36, 9.0.37', description: 'Componente de grilla de datos para Operato.' },
  { name: '@operato/graphql', versions: '9.0.22, 9.0.35, 9.0.36, 9.0.37, 9.0.38, 9.0.39, 9.0.40, 9.0.41, 9.0.42, 9.0.43, 9.0.44, 9.0.45, 9.0.46', description: 'Cliente GraphQL para Operato.' },
  { name: '@operato/headroom', versions: '9.0.2, 9.0.35, 9.0.36, 9.0.37', description: 'Componente Headroom para Operato.' },
  { name: '@operato/help', versions: '9.0.35, 9.0.36, 9.0.37, 9.0.38, 9.0.39, 9.0.40, 9.0.41, 9.0.42, 9.0.43, 9.0.44, 9.0.45, 9.0.46', description: 'Componentes de ayuda para Operato.' },
  { name: '@operato/i18n', versions: '9.0.35, 9.0.36, 9.0.37', description: 'Utilidades de internacionalización para Operato.' },
  { name: '@operato/input', versions: '9.0.27, 9.0.35, 9.0.36, 9.0.37, 9.0.38, 9.0.39, 9.0.40, 9.0.41, 9.0.42, 9.0.43, 9.0.44, 9.0.45, 9.0.46', description: 'Componentes de entrada para Operato.' },
  { name: '@operato/layout', versions: '9.0.35, 9.0.36, 9.0.37', description: 'Componentes de diseño para Operato.' },
  { name: '@operato/popup', versions: '9.0.22, 9.0.35, 9.0.36, 9.0.37, 9.0.38, 9.0.39, 9.0.40, 9.0.41, 9.0.42, 9.0.43, 9.0.44, 9.0.45, 9.0.46', description: 'Componente de popup para Operato.' },
  { name: '@operato/pull-to-refresh', versions: '9.0.36, 9.0.37, 9.0.38, 9.0.39, 9.0.40, 9.0.41, 9.0.42', description: 'Componente de pull-to-refresh para Operato.' },
  { name: '@operato/shell', versions: '9.0.22, 9.0.35, 9.0.36, 9.0.37, 9.0.38, 9.0.39', description: 'Componente de shell para Operato.' },
  { name: '@operato/styles', versions: '9.0.2, 9.0.35, 9.0.36, 9.0.37', description: 'Estilos para componentes Operato.' },
  { name: '@operato/utils', versions: '9.0.22, 9.0.35, 9.0.36, 9.0.37, 9.0.38, 9.0.39, 9.0.40, 9.0.41, 9.0.42, 9.0.43, 9.0.44, 9.0.45, 9.0.46', description: 'Utilidades para Operato.' },
  { name: '@teselagen/bounce-loader', versions: '0.3.16, 0.3.17', description: 'Un componente de cargador de rebote.' },
  { name: '@teselagen/liquibase-tools', versions: '0.4.1', description: 'Herramientas Liquibase para TeselaGen.' },
  { name: '@teselagen/range-utils', versions: '0.3.14, 0.3.15', description: 'Utilidades de rango para TeselaGen.' },
  { name: '@teselagen/react-list', versions: '0.8.19, 0.8.20', description: 'Un componente de lista virtualizado para React.' },
  { name: '@teselagen/react-table', versions: '6.10.19', description: 'Un componente de tabla para React.' },
  { name: '@thangved/callback-window', versions: '1.1.4', description: 'Una utilidad de ventana de callback.' },
  { name: '@things-factory/attachment-base', versions: '9.0.43, 9.0.44, 9.0.45, 9.0.46, 9.0.47, 9.0.48, 9.0.49, 9.0.50', description: 'Base de adjuntos para Things Factory.' },
  { name: '@things-factory/auth-base', versions: '9.0.43, 9.0.44, 9.0.45', description: 'Base de autenticación para Things Factory.' },
  { name: '@things-factory/email-base', versions: '9.0.42, 9.0.43, 9.0.44, 9.0.45, 9.0.46, 9.0.47, 9.0.48, 9.0.49, 9.0.50, 9.0.51, 9.0.52, 9.0.53, 9.0.54', description: 'Base de correo electrónico para Things Factory.' },
  { name: '@things-factory/env', versions: '9.0.42, 9.0.43, 9.0.44, 9.0.45', description: 'Utilidades de entorno para Things Factory.' },
  { name: '@things-factory/integration-base', versions: '9.0.43, 9.0.44, 9.0.45', description: 'Base de integración para Things Factory.' },
  { name: '@things-factory/integration-marketplace', versions: '9.0.43, 9.0.44, 9.0.45', description: 'Marketplace de integración para Things Factory.' },
  { name: '@things-factory/shell', versions: '9.0.43, 9.0.44, 9.0.45', description: 'Shell para aplicaciones de Things Factory.' },
  { name: '@tnf-dev/api', versions: '1.0.8', description: 'Utilidades de API para TNF-Dev.' },
  { name: '@tnf-dev/core', versions: '1.0.8', description: 'Utilidades principales para TNF-Dev.' },
  { name: '@tnf-dev/js', versions: '1.0.8', description: 'Utilidades de JavaScript para TNF-Dev.' },
  { name: '@tnf-dev/mui', versions: '1.0.8', description: 'Componentes de Material-UI para TNF-Dev.' },
  { name: '@tnf-dev/react', versions: '1.0.8', description: 'Utilidades de React para TNF-Dev.' },
  { name: '@ui-ux-gang/devextreme-angular-rpk', versions: '24.1.7', description: 'Componentes de DevExtreme Angular reempaquetados.' },
  { name: '@yoobic/design-system', versions: '6.5.17', description: 'Componentes del sistema de diseño de Yoobic.' },
  { name: '@yoobic/jpeg-camera-es6', versions: '1.0.13', description: 'Utilidad de cámara JPEG en ES6.' },
  { name: '@yoobic/yobi', versions: '8.7.53', description: 'Paquete principal de la aplicación Yoobic.' },
  { name: 'airchief', versions: '0.3.1', description: 'Una utilidad para gestionar entornos aislados.' },
  { name: 'airpilot', versions: '0.8.8', description: 'Una herramienta para pilotar aplicaciones.' },
  { name: 'angulartics2', versions: '14.1.1, 14.1.2', description: 'Analíticas agnósticas de proveedor para aplicaciones Angular.' },
  { name: 'browser-webdriver-downloader', versions: '3.0.8', description: 'Una herramienta para descargar WebDrivers de navegador.' },
  { name: 'capacitor-notificationhandler', versions: '0.0.2, 0.0.3', description: 'Plugin de manejador de notificaciones para Capacitor.' },
  { name: 'capacitor-plugin-healthapp', versions: '0.0.2, 0.0.3', description: 'Plugin de aplicación de salud para Capacitor.' },
  { name: 'capacitor-plugin-ihealth', versions: '1.1.8, 1.1.9', description: 'Plugin de iHealth para Capacitor.' },
  { name: 'capacitor-plugin-vonage', versions: '1.0.2, 1.0.3', description: 'Plugin de Vonage para Capacitor.' },
  { name: 'capacitorandroidpermissions', versions: '0.0.4, 0.0.5', description: 'Plugin de permisos de Android para Capacitor.' },
  { name: 'config-cordova', versions: '0.8.5', description: 'Herramienta de configuración para Cordova.' },
  { name: 'cordova-plugin-voxeet2', versions: '1.0.24', description: 'Plugin de Voxeet para Cordova.' },
  { name: 'cordova-voxeet', versions: '1.0.32', description: 'Plugin de Voxeet heredado para Cordova.' },
  { name: 'create-hest-app', versions: '0.1.9', description: 'CLI para crear una nueva aplicación Hestjs.' },
  { name: 'db-evo', versions: '1.1.4, 1.1.5', description: 'Herramienta de evolución de bases de datos.' },
  { name: 'devextreme-angular-rpk', versions: '21.2.8', description: 'Componentes de DevExtreme reempaquetados para Angular.' },
  { name: 'ember-browser-services', versions: '5.0.2, 5.0.3', description: 'Servicios de navegador para aplicaciones Ember.' },
  { name: 'ember-headless-form', versions: '1.1.2, 1.1.3', description: 'Componentes de formulario sin cabecera para Ember.' },
  { name: 'ember-headless-form-yup', versions: '1.0.1', description: 'Validación con Yup para ember-headless-form.' },
  { name: 'ember-headless-table', versions: '2.1.5, 2.1.6', description: 'Componentes de tabla sin cabecera para Ember.' },
  { name: 'ember-url-hash-polyfill', versions: '1.0.12, 1.0.13', description: 'Polyfill de hash de URL para Ember.' },
  { name: 'ember-velcro', versions: '2.2.1, 2.2.2', description: 'Un componente para anclar elementos en Ember.' },
  { name: 'encounter-playground', versions: '0.0.2, 0.0.3, 0.0.4, 0.0.5', description: 'Un playground para encuentros FHIR.' },
  { name: 'eslint-config-crowdstrike', versions: '11.0.2, 11.0.3', description: 'Configuración de ESLint para CrowdStrike.' },
  { name: 'eslint-config-crowdstrike-node', versions: '4.0.3, 4.0.4', description: 'Configuración de ESLint para Node.js de CrowdStrike.' },
  { name: 'eslint-config-teselagen', versions: '6.1.7', description: 'Configuración de ESLint para TeselaGen.' },
  { name: 'globalize-rpk', versions: '1.7.4', description: 'Librería Globalize reempaquetada.' },
  { name: 'graphql-sequelize-teselagen', versions: '5.3.8', description: 'Integración de GraphQL y Sequelize para TeselaGen.' },
  { name: 'html-to-base64-image', versions: '1.0.2', description: 'Convierte HTML a una imagen en base64.' },
  { name: 'json-rules-engine-simplified', versions: '0.2.1', description: 'Un motor de reglas simplificado usando JSON.' },
  { name: 'jumpgate', versions: '0.0.2', description: 'Una librería de componentes.' },
  { name: 'koa2-swagger-ui', versions: '5.11.1, 5.11.2', description: 'Swagger UI para Koa2.' },
  { name: 'mcfly-semantic-release', versions: '1.3.1', description: 'Configuración de semantic-release para McFly.' },
  { name: 'mcp-knowledge-base', versions: '0.0.2', description: 'Base de conocimiento para MCP.' },
  { name: 'mcp-knowledge-graph', versions: '1.2.1', description: 'Grafo de conocimiento para MCP.' },
  { name: 'mobioffice-cli', versions: '1.0.3', description: 'CLI para MobiOffice.' },
  { name: 'monorepo-next', versions: '13.0.1, 13.0.2', description: 'Utilidades de Next.js para monorepos.' },
  { name: 'mstate-angular', versions: '0.4.4', description: 'Gestión de estado para Angular.' },
  { name: 'mstate-cli', versions: '0.4.7', description: 'CLI para mstate.' },
  { name: 'mstate-dev-react', versions: '1.1.1', description: 'Herramientas de desarrollo para mstate en React.' },
  { name: 'mstate-react', versions: '1.6.5', description: 'Gestión de estado para React.' },
  { name: 'ng2-file-upload', versions: '7.0.2, 7.0.3, 8.0.1, 8.0.2, 8.0.3, 9.0.1', description: 'Componente de carga de archivos para Angular 2.' },
  { name: 'ngx-bootstrap', versions: '18.1.4, 19.0.3, 19.0.4, 20.0.3, 20.0.4, 20.0.5', description: 'Componentes de Bootstrap para Angular.' },
  { name: 'ngx-color', versions: '10.0.1, 10.0.2', description: 'Selector de color para Angular.' },
  { name: 'ngx-toastr', versions: '19.0.1, 19.0.2', description: 'Notificaciones emergentes (toast) para Angular.' },
  { name: 'ngx-trend', versions: '8.0.1', description: 'Componente de tendencia para Angular.' },
  { name: 'ngx-ws', versions: '1.1.5, 1.1.6', description: 'Módulo de WebSocket para Angular.' },
  { name: 'oradm-to-gql', versions: '35.0.14, 35.0.15', description: 'Una herramienta para convertir Orad-M a GraphQL.' },
  { name: 'oradm-to-sqlz', versions: '1.1.2', description: 'Una herramienta para convertir Orad-M a Sequelize.' },
  { name: 'ove-auto-annotate', versions: '0.0.9', description: 'Herramienta de anotación automática para OVE.' },
  { name: 'pm2-gelf-json', versions: '1.0.4, 1.0.5', description: 'Módulo de logging PM2 GELF JSON.' },
  { name: 'printjs-rpk', versions: '1.6.1', description: 'Librería Print.js reempaquetada.' },
  { name: 'react-complaint-image', versions: '0.0.32', description: 'Componente de imagen de queja para React.' },
  { name: 'react-jsonschema-form-conditionals', versions: '0.3.18', description: 'Lógica condicional para react-jsonschema-form.' },
  { name: 'remark-preset-lint-crowdstrike', versions: '4.0.1, 4.0.2', description: 'Preset de lint de Remark para CrowdStrike.' },
  { name: 'rxnt-authentication', versions: '0.0.3, 0.0.4, 0.0.5, 0.0.6', description: 'Librería de autenticación para RxNT.' },
  { name: 'rxnt-healthchecks-nestjs', versions: '1.0.2, 1.0.3, 1.0.4, 1.0.5', description: 'Chequeos de salud para NestJS en RxNT.' },
  { name: 'rxnt-kue', versions: '1.0.4, 1.0.5, 1.0.6, 1.0.7', description: 'Cola de trabajos Kue para RxNT.' },
  { name: 'swc-plugin-component-annotate', versions: '1.9.1, 1.9.2', description: 'Plugin de SWC para anotación de componentes.' },
  { name: 'tbssnch', versions: '1.0.2', description: 'Un paquete de utilidades.' },
  { name: 'teselagen-interval-tree', versions: '1.1.2', description: 'Implementación de árbol de intervalos para TeselaGen.' },
  { name: 'tg-client-query-builder', versions: '2.14.4, 2.14.5', description: 'Constructor de consultas de cliente para TeselaGen.' },
  { name: 'tg-redbird', versions: '1.3.1', description: 'Proxy inverso Redbird para TeselaGen.' },
  { name: 'tg-seq-gen', versions: '1.0.9, 1.0.10', description: 'Generación de secuencias para TeselaGen.' },
  { name: 'thangved-react-grid', versions: '1.0.3', description: 'Componente de cuadrícula para React.' },
  { name: 'ts-gaussian', versions: '3.0.5, 3.0.6', description: 'Librería de distribución gaussiana para TypeScript.' },
  { name: 'ts-imports', versions: '1.0.1, 1.0.2', description: 'Herramienta de gestión de importaciones de TypeScript.' },
  { name: 'tvi-cli', versions: '0.1.5', description: 'CLI para TVI.' },
  { name: 've-bamreader', versions: '0.2.6', description: 'Lector de archivos BAM para VectorEditor.' },
  { name: 've-editor', versions: '1.0.1', description: 'Componente de Vector Editor.' },
  { name: 'verror-extra', versions: '6.0.1', description: 'Utilidades extra para VError.' },
  { name: 'voip-callkit', versions: '1.0.2, 1.0.3', description: 'Plugin de CallKit para aplicaciones VoIP.' },
  { name: 'wdio-web-reporter', versions: '0.1.3', description: 'Reportero web para WebdriverIO.' },
  { name: 'yargs-help-output', versions: '5.0.3', description: 'Genera la salida de ayuda para yargs.' },
  { name: 'yoo-styles', versions: '6.0.326', description: 'Estilos para aplicaciones Yoo.' }
];
